### PR TITLE
update version to indicate v2.10 and higher is supported

### PR DESCRIPTION
**Pull request by hackerrdave**

### CODE REVIEW

**Comment by rmfitzpatrick** [comment]
@hackerrdave, thanks for your change.  Ideally this would be something we've confirmed by updating the tests: https://github.com/signalfx/signalfx-python-tracing/blob/master/noxfile.py#L290.  Would you want to parametrize the version as done elsewhere?  Otherwise I'd be happy to during one of my free moments.

**Comment by hackerrdave** [comment]
sure! will take a look

**Comment by hackerrdave** [comment]
@rmfitzpatrick - is that the correct test update?

**Comment by rmfitzpatrick** [comment]
@hackerrdave, I've made a minor correction, added the latest redis release, and added a connection check while standing up the redis integration tests.  Ok with these changes?

**Comment by hackerrdave** [comment]
LGTM! Thanks

**Pull request merged**
